---
title: "Exercise 1: Ready, Set, Smoke"
author: Prof. Dr. Nicolas Meseth
---

## OVERVIEW

In your first exercise, you make sure that you have everything you need to start with the LiFi-project. This includes the **hardware kit**, which requires some assembly, as well as a **development environment** on your computer. Finally, you run two different **smoke tests**.

Here are the relevant sections of the online script. Make sure you read everything carefully in order to solve this exercise:

-   [1 - Hardware Assembly](https://lifi.datalit.de/lifi-project/hardware-assembly)
-   [2 - Development Environment](https://lifi.datalit.de/lifi-project/development-environment)
-   [3 - Smoke Test](https://lifi.datalit.de/lifi-project/smoke-test)

Good Luck!

## YOUR TASKS

To pass this exercise, you must complete the following tasks and submit your results via [ILIAS](https://lms.hs-osnabrueck.de). You find the details on the form of submission below.

### 1. Assemble the Hardware

You should have an been provided with a hardware kit for the LiFi-project. For your first task, you need to assemble the separate hardware components into a hardware prototype for the LiFi-project. This involves some screwing and wiring. You find the detailed instructions in the [online script](https://lifi.datalit.de/lifi-project/hardware-assembly).

### 2. Install the Development Environment

In this task, install the necessary software for the development environment on your computer. You find all instructions and download links in the [online script](https://lifi.datalit.de/lifi-project/development-environment). As a reminder, here is a list of the software you need to install:

-   Brick Viewer and Brick Daemon
-   Visual Studio Code
-   Python
-   Git

### 3. Smoke Tests

Finally, you should run a number of tests to check your hardware and software setup.

*a) with the Brick Viewer*

1.  Connect your hardware kit to your computer using the provided USB cable.

2.  Open the Brick Viewer software on your computer.

3.  Connect to the hardware kit using the default host and port information. Check whether all devices are found and shown in separate tabs.

4.  Perform various tests, some ideas are documented in the online script.

*b) with a Python program*

1.  Check out the LiFi GitHub repository to download the `smoke_test.py` along with other code examples.

2.  Adjust the UID in the `examples/constants.py` file to reflect your devices.

3.  Open the file `examples/smoke_test.py` in Visual Studio Code.

4.  Run the program from a terminal and check the output for potential errors. If there are any errors, try to fix them.

5. Find out what the smoke test does. Play around with the hardware and see how changes to the rotary encoder affect the other components. You could also take a look at the code. Or both.

## SUBMISSION

For your first exercise, please submit:

-   One or more photos (.jpg or .png) of your assembled hardware kit.

-   A screenshot (.jpg or .png) from your computer in which the `smoke_test.py` is opened in Visual Studio Code, the code is running without errors, and the terminal shows the line "Please hit enter to exit".

Submit all files via the corresponding exercise in [ILIAS](https://lms.hs-osnabrueck.de).

{{< pagebreak >}}


## MORE EXERCISES TO PRACTICE

The following tasks are for you to practice your skills. They are optional and not part of the submission.

### 4. Play around with LiFi Example Code

For your development environment, you also installed Git on your computer. Git can be used to download code from platforms like GitHub to your local computer. For this course, many code examples (including the `smoke_test.py`) are provided via a GitHub repository. In the folder `/examples`, you will find scripts to see how each of the hardware devices can be programmed. Take look at them and see if you can run them.

### 5. Check For Firmware Updates

When you connect to your LiFi-hardware from the Tinkerforge Brick Viewer, you can check if all device's firmware is up-to-date. Run this check and update any devices if needed.


## MORE QUESTIONS TO PRACTICE

Try to answer the following questions to practice your understanding of the topics around the LiFi-project. The questions are optional and not part of the submission.

-   Do you know what the *firmware* of a hardware device is? Research the term and explain why we need it in your own words!
