---
title: "Exercise 5: Messages At The Speed Of Light"
author: Prof. Dr. Nicolas Meseth
---

::: {.callout-note appearance="simple"}
## Come Back Later

Great, you're ambitious and want to see what's awaiting you in this exercise! But you are ahead of your time - please check back later.
:::

## OVERVIEW

In the fifth exercise of the LiFi-project ...

Here are the relevant lessons of the online script. Make sure you study them carefully in order to solve this exercise:

-   [13 - Measuring Information](https://lifi.datalit.de/lifi-project/measuring-information)
-   [14 - The OLED Display](https://lifi.datalit.de/lifi-project/the-oled-display)
-   [15 - Very Light Messages](https://lifi.datalit.de/lifi-project/very-light-messages)

Good Luck!

## YOUR TASKS

To pass this exercise, you must complete the following tasks and submit your results via [ILIAS](https://lms.hs-osnabrueck.de). You find the details on the form of submission below.

### 1. ...

### 2. ...

### 3. ...

## SUBMISSION

For this exercise, please submit:

-   `...`

-   `...`

-   `...`

Submit all files via the corresponding exercise in [ILIAS](https://lms.hs-osnabrueck.de).

{{< pagebreak >}}

## MORE EXERCISES TO PRACTICE

The following tasks are for you to practice your skills. They are optional and not part of the submission.

### ...

### ...

## MORE QUESTIONS TO PRACTICE

Try to answer the following questions to practice your understanding of the topics around the LiFi-project. The questions are optional and not part of the submission.

-   ...
