---
title: "Exercise 6: Back To SMS"
author: Prof. Dr. Nicolas Meseth
---

## OVERVIEW

In the sixth exercise of the LiFi-project ...

Here are the relevant sections of the online script. Make sure you read everything carefully in order to solve this exercise:

-   [16 - Text Processing](https://lifi.datalit.de/lifi-project/text-processing)
-   [17 - Don't Repeat Yourself](https://lifi.datalit.de/lifi-project/do-not-repeat-yourself)
-   [18 - Text Messages](https://lifi.datalit.de/lifi-project/text-messages)

Good Luck!

## YOUR TASKS

To pass this exercise, you must complete the following tasks and submit your results via [ILIAS](https://lms.hs-osnabrueck.de). You find the details on the form of submission below.

### 1. ...

### 2. ...

### 3. ...

## SUBMISSION

For this exercise, please submit:

-   `...`

-   `...`

-   `...`

Submit all files via the corresponding exercise in [ILIAS](https://lms.hs-osnabrueck.de).

{{< pagebreak >}}

## MORE EXERCISES TO PRACTICE

The following tasks are for you to practice your skills. They are optional and not part of the submission.

### ...

### ...

## MORE QUESTIONS TO PRACTICE

Try to answer the following questions to practice your understanding of the topics around the LiFi-project. The questions are optional and not part of the submission.

-   ...
